---
title: "Supplementary material for Barrios Visibles"
author: Nissim Lebovits
affiliation: Independent Researcher
date: 2026-09-10
---

# Supplementary material

This file contains supporting tables and imagery for *Barrios Visibles: Building-footprint evidence of a systematic population undercount in Argentina's informal settlements*. The main article can be read independently and cites this supplement where relevant.


## S1 Sensitivity Analysis

Estimated households and population across building size filters, dwelling yields per footprint, and population multipliers. Per settlement, H = max(RENABAP families, footprints × y × 1.1), where y is the net number of occupied dwellings per mapped footprint. Range: 1,484,666 – 2,570,022 households; 4,157,065 – 8,609,576 population (8.9% – 18.4% of Argentina's total population).

| Size filter | Dwelling yield (y) | Pop mult | Buildings | Est. households | Est. population | % of Argentina |
| --- | --- | --- | --- | --- | --- | --- |
| No filter | 0.60 | 2.8 | 1,967,013 | 1,517,947 | 4,250,253 | 9.10% |
| No filter | 0.60 | 3.35 | 1,967,013 | 1,517,947 | 5,085,124 | 10.89% |
| No filter | 0.70 | 2.8 | 1,967,013 | 1,684,321 | 4,716,101 | 10.10% |
| No filter | 0.70 | 3.35 | 1,967,013 | 1,684,321 | 5,642,478 | 12.08% |
| No filter | 0.85 | 2.8 | 1,967,013 | 1,964,359 | 5,500,205 | 11.78% |
| No filter | 0.85 | 3.35 | 1,967,013 | 1,964,359 | 6,580,603 | 14.09% |
| No filter | 1.00 | 2.8 | 1,967,013 | 2,262,798 | 6,335,835 | 13.57% |
| No filter | 1.00 | 3.35 | 1,967,013 | 2,262,798 | 7,580,374 | 16.23% |
| No filter | 1.15 | 2.8 | 1,967,013 | 2,570,022 | 7,196,064 | 15.41% |
| No filter | 1.15 | 3.35 | 1,967,013 | 2,570,022 | 8,609,576 | 18.44% |
| ≥6 m² | 0.60 | 2.8 | 1,959,840 | 1,514,279 | 4,239,981 | 9.08% |
| ≥6 m² | 0.60 | 3.35 | 1,959,840 | 1,514,279 | 5,072,835 | 10.86% |
| ≥6 m² | 0.70 | 2.8 | 1,959,840 | 1,679,504 | 4,702,611 | 10.07% |
| ≥6 m² | 0.70 | 3.35 | 1,959,840 | 1,679,504 | 5,626,338 | 12.05% |
| ≥6 m² | 0.85 | 2.8 | 1,959,840 | 1,957,993 | 5,482,381 | 11.74% |
| ≥6 m² | 0.85 | 3.35 | 1,959,840 | 1,957,993 | 6,559,278 | 14.05% |
| ≥6 m² | 1.00 | 2.8 | 1,959,840 | 2,255,074 | 6,314,208 | 13.52% |
| ≥6 m² | 1.00 | 3.35 | 1,959,840 | 2,255,074 | 7,554,498 | 16.18% |
| ≥6 m² | 1.15 | 2.8 | 1,959,840 | 2,561,021 | 7,170,861 | 15.36% |
| ≥6 m² | 1.15 | 3.35 | 1,959,840 | 2,561,021 | 8,579,423 | 18.37% |
| ≥10 m² | 0.60 | 2.8 | 1,897,960 | 1,484,666 | 4,157,065 | 8.90% |
| ≥10 m² | 0.60 | 3.35 | 1,897,960 | 1,484,666 | 4,973,632 | 10.65% |
| ≥10 m² | 0.70 | 2.8 | 1,897,960 | 1,639,581 | 4,590,827 | 9.83% |
| ≥10 m² | 0.70 | 3.35 | 1,897,960 | 1,639,581 | 5,492,597 | 11.76% |
| ≥10 m² | 0.85 | 2.8 | 1,897,960 | 1,905,233 | 5,334,655 | 11.42% |
| ≥10 m² | 0.85 | 3.35 | 1,897,960 | 1,905,233 | 6,382,533 | 13.67% |
| ≥10 m² | 1.00 | 2.8 | 1,897,960 | 2,190,465 | 6,133,303 | 13.13% |
| ≥10 m² | 1.00 | 3.35 | 1,897,960 | 2,190,465 | 7,338,059 | 15.71% |
| ≥10 m² | 1.15 | 2.8 | 1,897,960 | 2,485,471 | 6,959,318 | 14.90% |
| ≥10 m² | 1.15 | 3.35 | 1,897,960 | 2,485,471 | 8,326,327 | 17.83% |

Aggregate parity yield (RENABAP families / 1.1 / footprints): 0.572 with no filter, 0.574 at ≥6 m², 0.593 at ≥10 m².

### S1.1 Which branch sets the floor, by yield

The columns count settlements in which the footprint branch or the RENABAP branch of the per-settlement maximum is larger at that yield.

| Size filter | y | Footprints higher | RENABAP higher |
| --- | --- | --- | --- |
| No filter | 0.60 | 3,894 | 2,573 |
| No filter | 0.70 | 4,729 | 1,738 |
| No filter | 0.85 | 5,450 | 1,017 |
| No filter | 1.00 | 5,803 | 664 |
| No filter | 1.15 | 6,042 | 425 |
| ≥6 m² | 0.60 | 3,861 | 2,602 |
| ≥6 m² | 0.70 | 4,715 | 1,748 |
| ≥6 m² | 0.85 | 5,436 | 1,027 |
| ≥6 m² | 1.00 | 5,796 | 667 |
| ≥6 m² | 1.15 | 6,039 | 424 |
| ≥10 m² | 0.60 | 3,602 | 2,861 |
| ≥10 m² | 0.70 | 4,558 | 1,905 |
| ≥10 m² | 0.85 | 5,342 | 1,121 |
| ≥10 m² | 1.00 | 5,739 | 724 |
| ≥10 m² | 1.15 | 5,995 | 468 |

## S2 Estimate Source by Urban Intersection

Share of settlements in which the building-footprint count (scaled by 1.1 at y = 1.00) versus the RENABAP family count established the per-settlement household floor, split by whether the settlement intersects an IGN Planta Urbana polygon.

| Urban? | Settlements | Used buildings | Used RENABAP | % buildings | % RENABAP |
| --- | --- | --- | --- | --- | --- |
| Yes | 5,380 | 4,805 | 575 | 89.3% | 10.7% |
| No | 1,083 | 998 | 85 | 92.2% | 7.8% |

## S3 Province Breakdown

| Provincia | Settlements | RENABAP | Buildings | Est. families | Used bldg | Used RENABAP |
| --- | --- | --- | --- | --- | --- | --- |
| Buenos Aires | 2,065 | 588,779 | 997,071 | 1,119,569 | 1,844 | 221 |
| Santa Fe | 469 | 92,776 | 134,103 | 153,171 | 413 | 56 |
| Chaco | 442 | 55,821 | 107,865 | 118,817 | 425 | 17 |
| Misiones | 413 | 58,322 | 87,582 | 99,990 | 344 | 69 |
| Tucumán | 370 | 48,003 | 82,136 | 92,044 | 356 | 14 |
| Ciudad Autónoma de Buenos Aires | 49 | 80,517 | 27,730 | 80,960 | 5 | 44 |
| Salta | 354 | 39,319 | 65,824 | 74,777 | 331 | 23 |
| Córdoba | 318 | 37,039 | 55,755 | 63,097 | 264 | 54 |
| Río Negro | 240 | 36,239 | 51,057 | 61,858 | 221 | 19 |
| Corrientes | 257 | 29,136 | 50,276 | 56,227 | 231 | 26 |
| Formosa | 126 | 27,942 | 48,742 | 54,533 | 114 | 12 |
| Mendoza | 360 | 26,432 | 47,634 | 52,618 | 342 | 18 |
| Santiago del Estero | 128 | 20,947 | 44,945 | 49,661 | 121 | 7 |
| Entre Ríos | 231 | 26,276 | 41,912 | 46,799 | 204 | 27 |
| Jujuy | 159 | 18,938 | 27,962 | 31,356 | 148 | 11 |
| Neuquén | 116 | 14,813 | 26,881 | 30,074 | 102 | 14 |
| Chubut | 83 | 10,660 | 19,862 | 22,219 | 76 | 7 |
| Tierra del Fuego | 49 | 6,147 | 11,524 | 12,722 | 43 | 6 |
| San Juan | 81 | 5,563 | 9,445 | 10,509 | 73 | 8 |
| San Luis | 32 | 4,442 | 7,912 | 8,714 | 27 | 5 |
| La Rioja | 34 | 2,476 | 6,715 | 7,387 | 34 | 0 |
| Catamarca | 61 | 3,936 | 6,490 | 7,350 | 55 | 6 |
| Santa Cruz | 21 | 2,863 | 6,539 | 7,193 | 21 | 0 |
| La Pampa | 9 | 409 | 1,051 | 1,156 | 9 | 0 |

## S4 Satellite Imagery

The following author-produced overlays are linked rather than redistributed pending confirmation of the underlying basemap's publication permissions:

- [Settlement example 1](https://nlebovits.github.io/ciut-riesgo/renabap_files/figure-html/fig-ejemplo-barrio-output-1.png)
- [Settlement example 2](https://nlebovits.github.io/ciut-riesgo/renabap_files/figure-html/fig-ejemplos-barrios-adicionales-output-1.png)
- [Settlement example 3](https://nlebovits.github.io/ciut-riesgo/renabap_files/figure-html/fig-ejemplos-barrios-adicionales-output-2.png)
- [Settlement example 4](https://nlebovits.github.io/ciut-riesgo/renabap_files/figure-html/fig-ejemplos-barrios-adicionales-output-4.png)


## S5 Census 2022 diagnostics

The article does not use these diagnostics. They compare allocated Census 2022 population with footprint-based population inside census radios covered by registered settlements, and they are retained here as supporting evidence. The comparison shares the footprint baseline with the article and is not an independent population count.

### S5.1 Complete coverage sweep

| Minimum tract coverage | Barrios | Footprints | Allocated Census population | Footprint-based population (×3.35) | Ratio |
| --- | ---: | ---: | ---: | ---: | ---: |
| 0% | 6,467 | 1,969,975 | 2,518,282 | 6,599,416 | 2.62 |
| 10% | 3,566 | 1,681,066 | 2,352,845 | 5,631,571 | 2.39 |
| 25% | 2,151 | 1,364,480 | 2,010,840 | 4,571,008 | 2.27 |
| 50% | 1,089 | 959,971 | 1,479,959 | 3,215,903 | 2.17 |
| 75% | 544 | 607,405 | 990,041 | 2,034,807 | 2.06 |
| 90% | 304 | 405,682 | 687,672 | 1,359,035 | 1.98 |
| 95% | 223 | 305,226 | 542,938 | 1,022,507 | 1.88 |

The Census comparison uses the earlier footprint join, which holds 1,969,975 footprints. The Paper I series reported in S1 holds 1,967,013. They differ by 2,962 footprints (0.15%) in 302 settlements, and the difference is confined to the 0% row.

### S5.2 Persons per enumerated private dwelling

These values divide population by VIV_TOT_P and diagnose occupancy at the aggregate level. Private dwellings may be unoccupied or contain more than one household, so these ratios cannot estimate household size.

| Scope | Radios | Population | Private dwellings | Persons per dwelling |
| --- | ---: | ---: | ---: | ---: |
| National file | 66,502 | 45,618,784 | 17,783,028 | 2.57 |
| All barrio-intersecting radios | 11,421 | 10,817,831 | 3,468,441 | 3.12 |
| Coverage ≥50% | 1,879 | 1,957,589 | 600,606 | 3.26 |
| Coverage ≥75% | 1,210 | 1,245,428 | 383,446 | 3.25 |
| Coverage ≥90% | 881 | 898,425 | 275,769 | 3.26 |
| Coverage ≥95% | 738 | 753,381 | 230,528 | 3.27 |

### S5.3 Multiplier sensitivity at 75% coverage

| Multiplier | Footprint-based population | Allocated Census population | Ratio |
| ---: | ---: | ---: | ---: |
| 2.80 | 1,700,734 | 990,041 | 1.72 |
| 3.12 | 1,895,104 | 990,041 | 1.91 |
| 3.35 | 2,034,807 | 990,041 | 2.06 |

### S5.4 Adjacent-radio diagnostic

The recovered validation pass classified radios with at least 1% barrio coverage, radios within 2 km but below that coverage, and more distant radios. The table reports urban radios only.

| Radio class | Radios | Population | Median population/km² | Persons per private dwelling |
| --- | ---: | ---: | ---: | ---: |
| Contains barrio | 7,695 | 7,795,633 | 8,720 | 3.18 |
| Border, below 1% coverage | 30,285 | 24,342,739 | 11,394 | 2.55 |
| Distant (>2 km) | 20,391 | 12,110,393 | 3,028 | 2.33 |

The saved output shows no elevated persons-per-private-dwelling ratio in adjacent radios. Raw density is higher because adjacent radios cluster in dense urban areas. The result cannot independently confirm that the national Census total is low. The validation output was preserved, but the exact distance-query implementation was not, so this table is not yet fully reproducible from the repository.

### S5.5 Provincial high-coverage comparison

The ≥75% subset is small in several provinces. These diagnostics are not used to make province-specific claims in the article.

| Province | Barrios | Footprints | Allocated Census population | Ratio (×3.35) |
| --- | ---: | ---: | ---: | ---: |
| Neuquén | 12 | 9,106 | 8,950 | 3.41 |
| Chaco | 29 | 23,839 | 24,816 | 3.22 |
| Tierra del Fuego | 13 | 3,779 | 4,186 | 3.02 |
| Río Negro | 22 | 17,253 | 20,126 | 2.87 |
| Buenos Aires | 283 | 379,062 | 616,392 | 2.06 |
| Ciudad Autónoma de Buenos Aires | 13 | 24,223 | 111,973 | 0.72 |

### S5.6 Dwelling-yield diagnostic against Census households

This diagnostic takes Census radios with RENABAP coverage at or above 95%, VIDA footprints of at least 10 m², and Census households from May 2022. The horizontal regime and all radios excluding CABA are reported as separate, overlapping strata, so the rows are not additive. Footprints are scaled by y × 1.1 for each tested dwelling yield and compared with Census households, and the 2022 to 2024 temporal mismatch is not corrected.

Break-even yield, at which footprints × y × 1.1 equals Census households: 0.553 in the horizontal regime and 0.544 excluding CABA.

| Stratum | y | Implied households | Census households | Ratio | Excess % |
| --- | ---: | ---: | ---: | ---: | ---: |
| Horizontal regime | 0.60 | 172,133 | 158,522 | 1.09 | +8.6% |
| Horizontal regime | 0.70 | 200,822 | 158,522 | 1.27 | +26.7% |
| Horizontal regime | 0.85 | 243,855 | 158,522 | 1.54 | +53.8% |
| Horizontal regime | 1.00 | 286,889 | 158,522 | 1.81 | +81.0% |
| Horizontal regime | 1.15 | 329,922 | 158,522 | 2.08 | +108.1% |
| Excluding CABA | 0.60 | 210,700 | 190,994 | 1.10 | +10.3% |
| Excluding CABA | 0.70 | 245,817 | 190,994 | 1.29 | +28.7% |
| Excluding CABA | 0.85 | 298,492 | 190,994 | 1.56 | +56.3% |
| Excluding CABA | 1.00 | 351,167 | 190,994 | 1.84 | +83.9% |
| Excluding CABA | 1.15 | 403,842 | 190,994 | 2.11 | +111.4% |

The growth analysis attributes about 20 percent of the excess above parity to construction after Census Day.
